services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    platform: linux/amd64
    restart: always
    volumes:
      - ./voicevox:/voicevox
    ports:
      - "50021:50021"

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  qdrant-data:
